apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-bck-storage-pv
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  storageClassName: "managed-nfs-storage"
  nfs: 
    path: /nfs-vol
    server: localhost
  persistentVolumeReclaimPolicy: Retain 
