apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-bck-storage-pvc
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "managed-nfs-storage"
